all:

clean:

install: all
	install -d $(INSTALLDIR)/usr/bin
	install kp_start $(INSTALLDIR)/usr/bin
	install kp_stop $(INSTALLDIR)/usr/bin
	install kp_restart $(INSTALLDIR)/usr/bin
	install -d $(INSTALLDIR)/usr/custom
	install koolproxy.sh $(INSTALLDIR)/usr/custom
	install wan-start.sh $(INSTALLDIR)/usr/custom
